name: talkwho
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  http: ^0.12.0+2
  flutter_custom_clippers: ^0.1.6
  html_unescape: ^1.0.1+2
  auto_size_text: ^2.0.0+2
  audioplayers: ^0.15.1
  audioplayer_web: ^0.7.1
  video_player: ">=0.7.0 <0.11.0"
  chewie: ^0.9.10
  auto_orientation: ^1.0.5
  flutter_tags: ^0.4.8
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.3+2
  flutter_staggered_animations: ^0.1.2
  clippy_flutter: ^1.1.1
  gradient_text: ^1.0.2
  transformer_page_view:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/click1.mp3
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300